### ISSUE TITLE
Agree Project Idea

### ISSUE THREAD

**Issue by DeeMcCart** [vinnieOrdobas/ci_national_ai#1]
EPIC:  AGILE(PM)

As a **team** we can **agree a project idea that we are all ignited by and prepared to commit to** so that **we can work to achieve a good delivierable within the hackathon**

### Assumptions or Pre-Requisites:
*  Requirements document (provided at hackathon outset)
*   and scoring document (provided 23/08/24 after meeting) ---- (see document attached to this issue, this is the later version from 23/08 including scoring)
*  Google sheet created to track project ideas and research https://docs.google.com/spreadsheets/d/1BCYA2D-KZ_gylJ2taCJopkSyHavqhHaKtNiJAh88uoA/edit?usp=sharing

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Must have a project idea agreed by team
- [x] Must communitate to sree@techireland on Saturday with 2-3 sentences about project idea

### Tasks

- [x] Task1 Team members - document suggestions on google sheet
- [x] Task2 Brainstorm during standup (Saturday) and check ideas against the requiremetns 
- [x] Task3 Identify futher research (problem solution, business case, and next steps

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

[National AI Challenge 2024 Guidelines 23_08_24.pdf](https://github.com/user-attachments/files/16736692/National.AI.Challenge.2024.Guidelines.23_08_24.pdf)

**Comment by DeeMcCart** [comment]
DECISION 24/08/24:    Housing portal to help someone who doesn't have secure housing to make a plan towards housing security 
* this could be secure rental in Ireland as a council/ Housing co-op tenant
* or it could be putting together the stepping-stones to purchase a home in Ireland
* or it could be a realisation that with the persons skills and abilities they may have a more secure future by emigration!
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>
4. How to get Housed in Ireland'RENT OR BUY'Acheiving long term housing stability | Possibly a combination of different datasets and matching including user criteria on income, location etc.Depends on querying different datasets (property price register, council boundaries etc) dont know if these dataasets are public facing available via APIs.Might be a bit tricky in this timescale. | Complexity   Vinnie top priority; Sean top priority; Possible tie-in with energy consumption/ green mortgages;Challenges of renting (ethical renting);Identify whether registered with RTB (is it possible to see previous rent charged on a public website)Challenges of dealing with poor supply (power currently sits with landlords)Escrow service for holding depositCredit rating/references for renters.How to plan a way forward - stay in famiy home with parents/ move abroad/ try to build/ try to purchaseExisting datasets:* social housing constructed & in-train dataset available on gov.ie (not geocoded, would need to be geocoded)* incentivise rural areaCould setup data on different schemes:  derelict housing grants; green mortgages; first home scheme. help to buy, shared ownershipMap view showig where someone wishes to live - returns average rental; property price registere.Persoal profile - is person locality-indepent (can they work remotely); .......... how to plan the route towards home ownership.Planapps dataset - is this still publicly available?  Could possibly extract data on housing estates.
-- | -- | --



</body>
</html>

**Comment by DeeMcCart** [comment]
-- PROJECT SUMMARY:

**Your personal AI guide to securing your first home. This intelligent chatbot combines data from diverse sources to offer tailored advice and actionable insights, helping you navigate the complexities of finding permanent housing. Get personalized recommendations and explore options that match your unique situation, all in one user-friendly platform.**
