### ISSUE TITLE
Create customer persona(s) & align with appropriate user stores/prompts

### ISSUE THREAD

**Issue by DeeMcCart** [vinnieOrdobas/ci_national_ai#20]
EPIC:  <epic>

As a **person currently living in non long-term/unstable housing in Ireland** I can **ask HomeIE  for guidance** so that **I am guided and advised with steps to achieves secure long-term housing**

### Assumptions or Pre-Requisites:
* Idea has been agreed #1 
* Initial user stories/prompts have been created

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] Must reflect a persona who we believe will be using the system and towards whom we target our content and offering
- [ ] May include serveral personas, but we need to be clear that we are trying to build a product suited to each
- [ ] Must be linked to user stories/ prompts reflecting how this person expects to interact with the system 

### Tasks

- [ ] Task1 Identify Persona
- [ ] Task2 List the user stories/ prompts that are linked to this persona
- [ ] Task3 Add more user stories/prompts if necessary to reflect this persona's needs
- [ ] Task4 

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
One persona (I interviewed him yesterday 26/0/24)
Name:  Owen
Job:  Business startup in Sportstech, earnings low
Currently living with his financee in 'granny flat' beside his parents house.
His family have some land and Joe applied for planning permission during 2024 so that he and his finacee could build a house on the family land.  They were refused.
Owen is now considering his position as he has spent a considerable amount of money getting this far and is really disappointed.  However he still believes it will be cheaper to build than buy.
He is unaware of any grant schemes which might help him towards building his own home but is very interested to find out more.

**Comment by valerieniloinsigh31** [comment]
Additional tailored user stories:

As a person currently living in non long-term/unstable housing in Ireland I can ask HomeIE for guidance on what options are available to me if I continue with the same career.

As a person currently living in non long-term/unstable housing in Ireland I can ask HomeIE for guidance on grants that I am likely to get.

As a person currently living in non long-term/unstable housing in Ireland I can ask HomeIE what the likely reason was for my planning permission application being rejected waa.

As a person currently living in non long-term/unstable housing in Ireland who is engaged, I can ask HomeIE for guidance on how my fiance and I can work together to secure a home.
