### ISSUE TITLE
Enhance Landing Page

### ISSUE THREAD

**Issue by DeeMcCart** [vinnieOrdobas/ci_national_ai#22]
EPIC:  <epic>

As a **user** I want to **use the landing page** to **understand the site purpose and how to use it**  

### Assumptions or Pre-Requisites:
* Wireframes done #1 
* MVP front-end site created #19 
*

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Disclaimer must include statement that this is entertainment site (refer to wireframe for text, theres one paragraph there to transfer)
- [ ] Link to privacy statement (text to be supplied)

### Tasks

- [x] Task1 Stefan please add any tasks here as required.
- [x] Task2 general cleanups were done Thurs 29th & Fri 30th.  One long landing page with team & contact details on it, hyperlinks from navbar to sections of this page

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
Is privacy statement still needed? for Thursday 05/09/24???
