### ISSUE TITLE
Create/Modify User Stories

### ISSUE THREAD

**Issue by DeeMcCart** [vinnieOrdobas/ci_national_ai#28]
EPIC:  SCOPE DEFINITION

As a **user** I want to **engage with the AI solution offered** to **access better-quality information than is availabile on standard chatbots in from the POV of a person living in accomodation without long-term security; who wishes to plan a progression towards secure long-term accomodation in Ireland**  
As a **user** I want to **engage with the AI solution offered** to **access territory-specific (Republic of Ireland) information on grants, and schemes and mechanisms which help me to progress towards secure long-term accomodation in Ireland**  

### Assumptions or Pre-Requisites:
* It is assumed that long term accomodation security is achieved either by:
- Purchasing a home
- Occupation of a social housing-owned property with security of tenure (Local Authority or Housing Co-op owned)
* The user stories generated must be in the form of prompt-response; with a stated expected response.
* The user stories generated will be used for manal testing of the trained model
* The user stories generated should be based on a Customer Persona (task #20 )
* Task XX refers to expected benefits of trained vs untrained AI model, how do we illustrate this with chatbot app?

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] A representative set of question-answer (prompt-response) 
- [x] Must be in the form of prompt-response; with a stated expected response
- [x] The user stories shoud each be tested on an untrained model and the results logged as a benchmark
- [x] When evaluating results, it may become clear that the prompt is insufficient.  In which case, please update the user story document 

### Tasks:  Note - User Stories to be logged in [Google Sheet](https://docs.google.com/spreadsheets/d/1BCYA2D-KZ_gylJ2taCJopkSyHavqhHaKtNiJAh88uoA/edit?usp=sharing)
- [x] Task1 Ensure user story aligns with a specific customer persona as documented in task #20 (create additional personas if needed, but don't go mad with it.)
- [x] Task2  Log the prompt you believe the customer persona will be making, 
- [x] Task3  Log the expected result (including format of output, e.g. text, chart, image, map) - note this might be specific dataset,  advice, numerical calculation that you reasonably expect
- [ ] Task4 Test the prompt in untrained gemini (just using gemini.google.com) to see what response you get.  Document it and classify as pass/fail (colour the cell green/red)
- [ ] Task5 If you believe a fail was because the prompt didnt include enough context (ie prompt & expectation not aligned) modify the prompt so that it gives enough information to arrive at the expected solution

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by valerieniloinsigh31** [comment]
<img width="1440" alt="Screenshot 2024-08-29 at 02 18 21" src="https://github.com/user-attachments/assets/df2bea48-d61e-4703-9e78-d7053e16056a">

**Comment by DeeMcCart** [comment]
This task is done just not quite as above...... the prompt-responses have effectively been built as training data.  User stories as per screenshot above have been developed, and have a role to play.
But, in real life, the model training / finetuning cycle would probably be undertaken in additional cycles and user stories refined in each cycle.
So the above is really just a snapshot or subset of what might be created.

**Comment by DeeMcCart** [comment]
Moved to 'done' 02/09/24 in Board cleanup - DMcC
