### ISSUE TITLE
Research Supporting Datasets for Chosen Idea

### ISSUE THREAD

**Issue by DeeMcCart** [vinnieOrdobas/ci_national_ai#4]
EPIC:  DATA

As a **AI developer** I can **use existing, high quality datasets** so that **The AI model can be supplied with relevant data**

### Assumptions or Pre-Requisites:
* Project idea has been agreed #1 
* Datasets exist which are relevant, current, authoritive 

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Must have list of usable datasets, including metadata and constraints
- [x] Must

### Tasks

- [x] Task1 Identify long-list of datasets for investigation
- [x] Task2 Focus and refine these as we understand more about AI capabilitiies
- [x] Task3 Refine list to usable subset

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
1. My Gov:  definitely have csv input on social housing started & completed (attached)

[csr-q1-2024.xlsx](https://github.com/user-attachments/files/16736954/csr-q1-2024.xlsx)

2.

**Comment by DeeMcCart** [comment]
(still work to process some of the data) 

Vinnie - 3 datasets (huggingface)
👍 Bloomberg
mortgage & loans
Financial - based on 8 source datasets (177K rows cleansed) - includes sentiment datasets
Sujet (may need to refer to source/copyright/license in readme)

Val - various datasets - housing driven - see google drive - ECB, gov.ie, RTB - harmonised index of consumer prices, CSO (e.g. rolling 12m rent)..... CBI..... note many of these datasets required tuning 
See 'Important links' on the AI Hackathon sheet.

(would like to have marginalised data if at all possible)


Sean - see google drive

**Comment by valerieniloinsigh31** [comment]
<img width="1440" alt="Screenshot 2024-08-28 at 20 57 48" src="https://github.com/user-attachments/assets/7d84e479-8695-42c1-ac42-9f80ba66bd7e">

**Comment by DeeMcCart** [comment]
DMcC 02/09/24 Moving to Done
