### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by DeeMcCart** [vinnieOrdobas/ci_national_ai#50]
EPIC:  Investor Pitch

As a **user** I want to **use HomeIE chatbot in a language of my choosing** to achieve **direct communication without needing to use an external translation software/service**  

### Assumptions or Pre-Requisites:
* HomeIE Chatbot is in place and can be tested
*
*

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] Must recognise and respond to the language the user types in
- [ ] Acceptable number of prompt-responses before switchover (immediate? after a couple of back-and-forths?)

### Tasks

- [x] Task1  Test in German
- [x] Task2  Test in French
- [x] Task3  Test in Ukranian
- [x] Task4  Test in Irish

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
Summary of results:
![240902 Multilingual testing - results](https://github.com/user-attachments/assets/146104a6-401c-4bc7-80fc-b7babdca4110)

Testing document:
[240902 Multilingual Testing.docx](https://github.com/user-attachments/files/16835785/240902.Multilingual.Testing.docx)

**Comment by valerieniloinsigh31** [comment]
German testing - language detected on first response
<img width="1440" alt="Screenshot 2024-09-02 at 18 27 09" src="https://github.com/user-attachments/assets/9783a803-1cc8-484a-b3eb-81d0f2ff80ca">

**Comment by valerieniloinsigh31** [comment]
Limitation observed when switching languages mid-chat. Chatbot responds with the language of the initial question regardless of whether further questions are posed in a different language. E.g. if initial question asked in German, Chatbot will continue to respond in German regardless of several subsequent questions are posed in French (see attached). Consider adding 'Language change' button (with dropdown of selected languages) or chat reset button (that would just refresh tab
<img width="1440" alt="Screenshot 2024-09-02 at 18 28 47" src="https://github.com/user-attachments/assets/fc79dad0-6321-4c2c-ae18-95f5de9084e3">

**Comment by valerieniloinsigh31** [comment]
Ukranian detected on initial question:
<img width="1440" alt="Screenshot 2024-09-02 at 18 56 13" src="https://github.com/user-attachments/assets/926071fa-8892-456a-9cfb-48c3a85db946">

**Comment by valerieniloinsigh31** [comment]
Transitioned successfully from Ukranian to Irish within the same chat, with a stopgap response in between from Chat GPT summarizing form input. Had to ask Irish question twice before Irish response received
<img width="1440" alt="Screenshot 2024-09-02 at 18 59 41" src="https://github.com/user-attachments/assets/ee8a78c5-9744-42f6-ae4e-c5ad711602fc">

**Comment by DeeMcCart** [comment]
DMcC 2/09/24 hmmm its definitely not perfect but adequate for now given time contraints - needs to be listed as a future enhacement.  Moving to 'done'
