### ISSUE TITLE
Define/ Decribe Solution Architecture

### ISSUE THREAD

**Issue by DeeMcCart** [vinnieOrdobas/ci_national_ai#6]
EPIC:  Final Delivered Solution

As a **team member** I want to **understand the solution architecture** to achieve **co-ordinate building as a team; include in ReadMe and clearly explain to audience/judges**  

### Assumptions or Pre-Requisites:
* We are likely to have a 'front-end' (well actually be a front-end + back-end as includes HTML CSS Javascript Python Django & ReadMe).  This will be worked on in Repo ci_national_ai  
* During development a 2nd repo will hold the AI work*
* It is likely that the deliverable will either consist of:
- a front end 'traditional ' repo which uses API calls to trained AI models
- a front end 'traditional' repo which acts as a skin to a fully-functional AI solution

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Need an architecture diagram showing how the different applciation layers (esp presentation layer) inter-operate
- [ ] Must be functional????

### Tasks

- [x] Task1 Work it out over the course of the week to hackathon
- [ ] Task2
- [ ] Task3
- [ ] Task4

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
DMcC 02/09/24:  see wireframes and solution architecture diagram



![Image](https://github.com/user-attachments/assets/3ca6f9a0-0155-40bb-92de-49a26750b69d)

**Comment by DeeMcCart** [comment]
![Image](https://github.com/user-attachments/assets/82e14c12-f09d-4ff0-ad79-996a9aa9582a)
