### ISSUE TITLE
Create ReadMe Structure

### ISSUE THREAD

**Issue by DeeMcCart** [vinnieOrdobas/ci_national_ai#7]
EPIC:  <epic>

As a **hackathoner** I want to **describe the developed solution** to **prove that each of the hackathon criteria has been met, and to build the body of knowledge for anyone wishing to progress this or a similar solution in the future**  

### Assumptions or Pre-Requisites:
* Idea is decided #1
* Maintaining the Readme will be an ongoing task over the life of the hackathon
*Include detail on planning (Agile/Stand-Ups/Sprints).
*Include detail on data-set sources and fine tuning
*Insert Wireframe

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Must have section outlines and table of contents
- [x] ? Document what we know about the problem ?

### Tasks

- [x] Task1 Create structure
- [x] Task2 Start creating content where possible (Problem and solution)
- [x] Task3 Insert Sources
- [x] Task4 Insert images of planing - shared excel
- [x] Task5 Wireframe
- [ ] Insert code validations

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by valerieniloinsigh31** [comment]
<img width="1440" alt="Screenshot 2024-08-29 at 01 59 46" src="https://github.com/user-attachments/assets/2e463446-6818-4919-ba8e-fbb84eac6c9e">

**Comment by DeeMcCart** [comment]
DMcC 02/09/24 Created updated & deployed last week - moving to staus 'done'
