### ISSUE TITLE
Create Wireframe (First version)

### ISSUE THREAD

**Issue by DeeMcCart** [vinnieOrdobas/ci_national_ai#8]
EPIC:  #12

As a **team member** I want to **see/understand/update wireframe** to achieve **understand project goals & objectives**  

### Assumptions or Pre-Requisites:
* #1 Idea is agreed
* #5 Some idea of what the solution might contain

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] Must be viewed by each participating team member
- [ ] Finalise before project is completed (doesnt need to be exactly the same as final deliverable, but should be revised if it's wildly different)

### Tasks

- [x] Task1 Create first draft 25/08
- [x] Task2 Team to review and comment/suggest changes or clarifications (done @ standup 25/08/24 a.m.)
- [ ] Task3 Revise
- [ ] Task4 Finalise and contribute to readme

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
![Image](https://github.com/user-attachments/assets/5b98072e-ec3b-4d50-9b06-5bea9131ba08)



![Image](https://github.com/user-attachments/assets/349ff58b-4852-4b82-bcc6-2d03912952fd)



![Image](https://github.com/user-attachments/assets/a5257b3f-4503-4245-9422-c7ba6f8e8f49)



![Image](https://github.com/user-attachments/assets/6146d1e1-6fd2-49b8-95ac-0135bf7fc97c)
